name: Build and test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ahmed0rashed0/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true ahmed0rashed0/react-test npm run test


      # - run : docker build -t ahmedgamil/multi-client ./microservices/client 
      # - run : docker build -t ahmedgamil/multi-server ./microservices/server
      # - run : docker build -t ahmedgamil/multi-worker ./microservices/worker
      # - run : docker build -t ahmedgamil/multi-nginx ./microservices/nginx

      # - run : docker push ahmedgamil/multi-client
      # - run : docker push ahmedgamil/multi-server
      # - run : docker push ahmedgamil/multi-worker
      # - run : docker push ahmedgamil/multi-nginx

#       - name: create deployment package
#         run: zip -r deploy.zip . -x '*.git*'

#       - name: Deploy over elastic beanstalks 
#         uses: einaregilsson/beanstalk-deploy@v22
#         with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          application_name: react
#          environment_name: React-env
#          version_label: ${{github.sha}}
#          region: us-east-1
#          deployment_package: deploy.zip